/*
 * Version Number: 1.1.0
 * User Story Number: US01
 * Date & Time of Change: 2026-07-14T13:01:40+05:30
 * User Name: Satish
 * Brief Description of Change: Added invoices table for billing.
 */
DROP TABLE invoices IF EXISTS;
DROP TABLE appointments IF EXISTS;
DROP TABLE vet_specialties IF EXISTS;
DROP TABLE vets IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE pets IF EXISTS;
DROP TABLE types IF EXISTS;
DROP TABLE owners IF EXISTS;


CREATE TABLE vets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR(30)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL
);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR_IGNORECASE(30),
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(30),
  birth_date DATE,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER NOT NULL
);
ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INTEGER NOT NULL,
  visit_date  DATE,
  description VARCHAR(255)
);
ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX visits_pet_id ON visits (pet_id);

CREATE TABLE appointments (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id           INTEGER NOT NULL,
  vet_id           INTEGER NOT NULL,
  appointment_date DATE NOT NULL,
  time_slot        VARCHAR(10) NOT NULL,
  description      VARCHAR(255) NOT NULL,
  status           VARCHAR(20) NOT NULL
);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX appointments_pet_id ON appointments (pet_id);
CREATE INDEX appointments_vet_id ON appointments (vet_id);

CREATE TABLE invoices (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id         INTEGER NOT NULL,
  visit_id         INTEGER,
  appointment_id   INTEGER,
  amount           DECIMAL(10, 2) NOT NULL,
  issue_date       DATE NOT NULL,
  due_date         DATE NOT NULL,
  payment_status   VARCHAR(20) NOT NULL,
  payment_date     DATE,
  description      VARCHAR(255) NOT NULL
);
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_visits FOREIGN KEY (visit_id) REFERENCES visits (id);
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_appointments FOREIGN KEY (appointment_id) REFERENCES appointments (id);
CREATE INDEX invoices_owner_id ON invoices (owner_id);


